# This is an autogenerated file. Do not edit manually unless you are feeling adventurous
from dynamic_types import *
admin_tags = dict()
race_tags = dict()

admin_tags['988318022124501a7e']=color_change

race_tags['80000c007717605f2f']=banana
